# Generated by Django 2.1.5 on 2019-01-11 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=1000)),
                ('schedule', models.TimeField()),
                ('condition', models.TextField()),
                ('STATUS', models.CharField(choices=[('ACT', 'Activate'), ('DACT', 'Deactivate')], default='ACT', max_length=2)),
                ('campaigns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbengine.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='VariableMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_id', models.CharField(max_length=500)),
                ('impression', models.IntegerField(blank=True, null=True)),
                ('click', models.IntegerField(blank=True, null=True)),
                ('install', models.IntegerField(blank=True, null=True)),
                ('spend', models.IntegerField(blank=True, null=True)),
                ('ecpm', models.IntegerField(blank=True, null=True)),
                ('ecpi', models.IntegerField(blank=True, null=True)),
                ('rules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rbengine.Rule')),
            ],
        ),
    ]
