# Generated by Django 2.1.5 on 2019-01-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='ACTION',
            field=models.CharField(choices=[('Notify', 'Notify'), ('St', 'Start'), ('Pa', 'Pause')], default='Notify', max_length=2),
        ),
    ]
