# Generated by Django 2.1.5 on 2019-01-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbengine', '0002_rule_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='ACTION',
            field=models.CharField(choices=[('Notify', 'Notify'), ('St', 'Start'), ('Pa', 'Pause')], default='Notify', max_length=1000),
        ),
        migrations.AlterField(
            model_name='rule',
            name='STATUS',
            field=models.CharField(choices=[('ACT', 'Activate'), ('DACT', 'Deactivate')], default='ACT', max_length=1000),
        ),
    ]
